# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

############
# Solution #
############

def P(n):
	return n * (3 * n - 1) // 2
def H(n):
	return n * (2 * n - 1)
def T(n):
	return n * (n + 1) // 2

n_t = 286
n_p = 165
n_h = 143
limit = 100000
while n_t < limit:
	t_n = T(n_t)
	p_n = P(n_p)
	h_n = H(n_h)

	while p_n < t_n:
		n_p += 1
		p_n = P(n_p)

	while h_n < t_n:
		n_h += 1
		h_n = H(n_h)

	if p_n == h_n and h_n == t_n:
		print(t_n)
		break
	n_t += 1